### ISSUE TITLE
Geef een titel aan je document

### ISSUE THREAD

**Issue by zoepje** [J3SS3HVA/the-startup-responsive-interactieve-website#1]
https://github.com/J3SS3HVA/the-startup-responsive-interactieve-website/blob/15f9bfefadbccf5e768337a55f0ece5052894a88/index.html#L6

Geef de titel van de pagina ipv "Document".

**Comment by Jesse-L3** [comment]
` <title>Lifely AI getting started</title>`

titel is toegevoegd
