### ISSUE TITLE
Zelfsluitende tag

### ISSUE THREAD

**Issue by Naddybs** [J3SS3HVA/the-startup-responsive-interactieve-website#11]
https://github.com/J3SS3HVA/the-startup-responsive-interactieve-website/blob/15f9bfefadbccf5e768337a55f0ece5052894a88/index.html#L4

Zie ook regel 5 en 7

Backlash is niet nodig het is een zelfsluitende tag

**Comment by Jesse-L3** [comment]
`<meta charset="UTF-8">`

alles in de head hebben geen / aan het einde meer
