### ISSUE TITLE
back slash onnodig gebruik

### ISSUE THREAD

**Issue by BibekMA** [J3SS3HVA/the-startup-responsive-interactieve-website#16]
Je hebt een aantal keren backslash gebruikt wanneer het eigenlijk niet hoeft, dus misschien kan je even kijken daarna en die weghalen en checken of het nog goed staat daarna

https://github.com/J3SS3HVA/the-startup-responsive-interactieve-website/blob/9515ffe87502fef1577f3b0231b4b030d14a10ee/index.html#L7

**Comment by Jesse-L3** [comment]
`<link rel="icon" href="assets/logos/Favicon/Favicon_homerun _red.png" type="image/x-icon">`

hier is een voorbeeld. overal waar een path staat word nu met forward slashes gebruikt
