### ISSUE TITLE
De hr element in ol

### ISSUE THREAD

**Issue by BibekMA** [J3SS3HVA/the-startup-responsive-interactieve-website#17]
Je hebt een hr in een ol staan, en dat is in deze context eigenlijk niet de bedoeling 

https://github.com/J3SS3HVA/the-startup-responsive-interactieve-website/blob/9515ffe87502fef1577f3b0231b4b030d14a10ee/index.html#L156

**Comment by Jesse-L3** [comment]
`  <li>
            <span>Step 5 </span>
            <h3>And we make sure it works</h3>
            <h4>Solve for good.</h4>
            <p>
              We bring back your team to test the prototype and see if it’s
              helpful and practical in real-world scenarios. In the end, you’ll
              receive the actual prototype (be it an API or script), and advice
              on whether or not your organisation is ready to embrace AI.
            </p>
            <hr>
          </li>  `

de hr is nu een child element in de li en niet meer de ol
