### ISSUE TITLE
Span element wel afgesloten maar niet echt netjes 

### ISSUE THREAD

**Issue by Jason2426** [J3SS3HVA/the-startup-responsive-interactieve-website#2]
https://github.com/J3SS3HVA/the-startup-responsive-interactieve-website/blob/15f9bfefadbccf5e768337a55f0ece5052894a88/index.html#L20C9-L22

**Comment by Jesse-L3** [comment]
<div>
        <span>
          <a href="">Call us <b>020 846 19 05</b></a>
        </span>
        <span>
          <a href="contact">contact</a>
        </span>
        <span>
          <a href="">menu</a>
        </span>
      </div>

heb ze netjes gesloten
