### ISSUE TITLE
Gebruik inline CSS in HTML

### ISSUE THREAD

**Issue by MokhtarAkle** [J3SS3HVA/the-startup-responsive-interactieve-website#23]
https://github.com/J3SS3HVA/the-startup-responsive-interactieve-website/blob/9515ffe87502fef1577f3b0231b4b030d14a10ee/index.html#L68

Probeer CSS niet in-line met HTML te gebruiken om de semantiek correct te houden en toegankelijkheid te verbeteren. In dit geval zou een ID of een selector hetzelfde voor je kunnen doen terwijl jij je aan de "best practices" kan houden.

https://www.codecademy.com/article/html-inline-styles

**Comment by Jesse-L3** [comment]
dat klopt die is van de form waarin de kalender zit. die heb ik zelf niet gemaakt
