### ISSUE TITLE
Verschillende code conventie voor class names

### ISSUE THREAD

**Issue by Ryank2004** [J3SS3HVA/the-startup-responsive-interactieve-website#26]
https://github.com/J3SS3HVA/the-startup-responsive-interactieve-website/blob/9515ffe87502fef1577f3b0231b4b030d14a10ee/index.html#L12C18-L12C27

Hier gebruik je - tussen woorden.

https://github.com/J3SS3HVA/the-startup-responsive-interactieve-website/blob/9515ffe87502fef1577f3b0231b4b030d14a10ee/index.html#L14C15-L14C30

Hier gebruik je camelCasing.

https://github.com/J3SS3HVA/the-startup-responsive-interactieve-website/blob/9515ffe87502fef1577f3b0231b4b030d14a10ee/index.html#L34

Hier gebruik je voor beide woorden een hoofdletter.

Probeer een conventie te vinden die je altijd gebruikt. Zo voorkom je spelfouten met het linken van je CSS aan je HTML.

**Comment by Jesse-L3** [comment]
`<section class="starting">
        <div class="starting-primary">`

hier zijn 2 voorbeelden waarbij ik de hoofdletters heb weg gehaald
