### ISSUE TITLE
Geef je linkjes een href

### ISSUE THREAD

**Issue by zoepje** [J3SS3HVA/the-startup-responsive-interactieve-website#3]
https://github.com/J3SS3HVA/the-startup-responsive-interactieve-website/blob/15f9bfefadbccf5e768337a55f0ece5052894a88/index.html#L46-L47

Waar leiden deze linkjes naar toe?

**Comment by Jesse-L3** [comment]
`<span><a href="https://lifely.nl/en/">home/</a></span>

 <span><a href="https://lifely.nl/en/solutions/">Solutions/</a></span>
        
<span><a href="Getting Started with Artificial Intelligence">Getting Started with Artificial Intelligence</a></span>`

hyperlinks hebben nu een linkje in hun href hierboven zie je een voorbeeld van wat er in mijn nav zit
