### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by Naddybs** [J3SS3HVA/the-startup-responsive-interactieve-website#7]
https://github.com/J3SS3HVA/the-startup-responsive-interactieve-website/blob/15f9bfefadbccf5e768337a55f0ece5052894a88/index.html#L44

- Image tags hoef je niet te sluiten met een backlash.
- vergeet ALT teksten niet voor images

**Comment by Jesse-L3** [comment]
Alle images hebben nu geen / aan het einde hier is een example

![saved](https://github.com/J3SS3HVA/the-startup-responsive-interactieve-website/assets/144009667/b2cdf36d-4afd-49fb-9c89-559d434610ee)
